HaveakPro/Areas/SINAV/Controllers/TipEgitimTestController.cs
using HaveakPro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Web.UI;

namespace HaveakPro.Areas.SINAV.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*", Location = OutputCacheLocation.None)]
    [Authorize]
    public class TipEgitimTestController : Controller
    {
      
        HaveakEntities entity;
        public TipEgitimTestController(HaveakEntities _entity)
        {
            entity = _entity;
        }

        public async Task<ActionResult> TipEgitimTesteBasla(int id)
        {
            ViewBag.TipEgitimtestID = id;
            List<TipEgitim_Sorular> data = null;
            if (Session["Sorular"] == null)
            {
                data = await entity.TipEgitim_Sorular.OrderBy(x => Guid.NewGuid()).Where(r => r.TipEgitSinavlar_Ref == id && r.IsActive == true && r.IsDelete == false).ToListAsync();
                Session["Sorular"] = data;
            }
            else
            {
                data = Session["Sorular"] as List<TipEgitim_Sorular>;
            }
            Session["SoruIceriklerListe"] = null;
            return View(data);
        }
        public JsonResult TipEgitimTestBitir()
        {
            Session["Sorular"] = null;
            Session["SoruIceriklerListe"] = null;
            Session["SoruIcerikler"] = null;
            return Json(true, "application/json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
       
        public ActionResult _TSoruDetay(int TipEgitim_Ref, int idx, int Kalansoru)
        {
            List<TipEgitim_Sorular> sorular = null;
            sorular = Session["Sorular"] as List<TipEgitim_Sorular>;
            int index = 0;         

            List<SoruDetaylar> SoruListe = new List<SoruDetaylar>();
            foreach (var item in sorular)
            {
                index++;
                int toplamSoru = sorular.Count;
                int kalan = toplamSoru - index;       
                SoruListe.Add(new SoruDetaylar{ Kalan = kalan, Sira= index, SoruNo = item.ID });
            }
            SoruDetaylar detaySoru = SoruListe.Where(r => r.SoruNo == idx).Select(w => new SoruDetaylar { Sira = w.Sira, SoruNo = w.SoruNo, Kalan = w.Kalan }).FirstOrDefault();
            int nextID = SoruListe.SkipWhile(i => i.SoruNo != idx)
                .Skip(1)
                .Select(i => i.SoruNo).FirstOrDefault();              
            ViewBag.SonrakiSoru = nextID;     
            Session["SoruIcerikler"] = detaySoru;
            if (Session["SoruIceriklerListe"] == null)
            {
                Session["SoruIceriklerListe"] = SoruListe;
            }
            ViewBag.SoruSonucListe = (List<SoruDetaylar>)Session["SoruIceriklerListe"];
            ViewBag.Kalansoru = Kalansoru;
            TipEgitim_Sorular data = sorular.Where(t => t.ID == idx).FirstOrDefault();            
            return PartialView("_SoruIcerikEgitimTip", data);
        }

        public async Task<JsonResult> SoruCevapla(int soruRef, string girilenCevap, bool? koordinatSecim)
        {            
            bool sonuc = false;
            string cevap = "Seçim Doğru";
            try
            {
                var soruDetay = await entity.TipEgitim_Sorular.Where(t => t.ID == soruRef).FirstOrDefaultAsync();                
                var dogruCevap = soruDetay.UniteSorular.SoruSiklaris.Where(t => t.IsActive == true && t.IsDelete == false && t.DogruSecenek == true).Select(w => w.SoruSikki).FirstOrDefault();
                if (girilenCevap == "a)")
                {
                    if (dogruCevap == girilenCevap)
                    {
                        sonuc = true;
                    }
                    else
                    {
                        sonuc = false;
                        if (dogruCevap == "b)")
                        {
                            string maddeTuru = soruDetay.UniteSorular.SBMaddeResimler.SBTehlikeliMKategori.Isim;
                            cevap = "Tehlikeli madde ('" + maddeTuru + "') bulunmaktadır!";
                        }
                        else
                        {
                            cevap = "Soruda tehlikeli madde yoktur";
                        }
                    }
                }
                else
                {

                    if (girilenCevap == "b)" && koordinatSecim == true)
                    {
                        sonuc = true;                         
                    }
                    else
                    {
                        sonuc = false;
                        string maddeTuru = soruDetay.UniteSorular.SBMaddeResimler.SBTehlikeliMKategori.Isim;
                        cevap = "Maddenin ('" + maddeTuru + "') yerini işaretleyiniz!";                                             
                    }
                }
            }
            catch
            {
                sonuc = false;
                cevap = "Soruda tehlikeli madde yoktur";
            }
            var dataSorular = (List<SoruDetaylar>)Session["SoruIceriklerListe"];
            var isle = dataSorular.Where(w => w.SoruNo == soruRef).First();
            isle.Cevap = sonuc;
            Session["SoruIceriklerListe"] = dataSorular;
            return Json(cevap, "application/json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }

    public class SoruDetaylar:IDisposable
    {
        public int SoruNo { get; set; }
        public int Sira { get; set; }
        public int Kalan { get; set; }
        public bool? Cevap { get; set; }
        public void Dispose()
        {
            GC.SuppressFinalize(this);
        }
    }
}

HaveakPro/Areas/SINAV/Views/TipEgitimTest/TipEgitimTesteBasla.cshtml
@model List<TipEgitim_Sorular>
@{
    ViewBag.Title = "TipTesteBasla";
    Layout = "~/Views/Shared/_LBagaj.cshtml";
    //int personel = Authorizing..User_Ref;
    //HaveakEntities Entity = new HaveakEntities();
    //TimeSpan bitisSaati;

    //var aktifSinav = (Personel_TIP)ViewBag.Per_TIP;
    int SinavID = (int)ViewBag.TipEgitimtestID;
    //int basladi = 0;
    //int bitti = 0;
    //int Personel_TipRef = Model.Select(r => r.TipSinavlar_Ref).FirstOrDefault();
    //var zamanlar = Entity.Personel_TIP.Where(t => t.ID == Personel_TipRef).FirstOrDefault();
    DateTime zaman = DateTime.Now;

    //var SOgrenciRef = Entity.Sinif_Ogrenci.Where(t => t.Bitti == false && t.Personel_Ref == personel).Select(e => e.ID).FirstOrDefault();
    //if (aktifSinav != null)
    //{
    //bitisSaati = zamanlar.CikisSaati.Value;
    //if (aktifSinav.Basladi == 1)
    //{
    //    basladi = aktifSinav.Basladi.Value;
    //    bitti = aktifSinav.Bitti;
    //}
    //}
    //string soruKontrol = basladi == 1 ? "block" : "none";
    //var testler = Model.Select(t => new { t.TipSinavlar_Ref, t.TipSinavlar.Sure }).FirstOrDefault();
    //var per_test = Entity.Personel_TIP.Where(r => r.Personel_Ref == personel && r.TipSinavlar_Ref == testler.TipSinavlar_Ref).Select(t => new { t.ID, t.GirisSaati, t.TipSuresi, t.Basladi, t.Bitti }).FirstOrDefault();
    //if (per_test != null)
    //{
    //    basladi = per_test.Basladi.Value;
    //}

    int testSure = Model.Select(q => q.TipEgitimSinavlar.Sure).FirstOrDefault();
    DateTime testtoplamSuresi = zaman.AddMinutes(testSure);
    string bitisSaati = testtoplamSuresi.TimeOfDay.Hours + ":" + testtoplamSuresi.TimeOfDay.Minutes + ":" + testtoplamSuresi.TimeOfDay.Seconds;

    int? sorunNo = (int?)ViewBag.Soruno;
    int kalansoru = 0;
    if (sorunNo == null)
    {
        sorunNo = Model.Select(e => e.ID).FirstOrDefault();
        kalansoru = Model.Count;
    }


                            //ViewBag.NextID = nextID;
}
@using HaveakPro.Models;
@using HaveakPro.Areas.SINAV.Controllers;

<div class="content-frame">
    <ul class="breadcrumb">
        <li></li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div id="seciliSoruIcerik" style="height: 430px;">
            </div>          
          
        </div>

       
    </div>

</div>
<br />
<br />

</div>
<button type="button" id="uyari" class="btn btn-warning mb-control" data-box="#message-box-warning" style="visibility: hidden"></button>
<button type="button" id="kapatma" class="btn btn-danger mb-control" data-box="#message-box-sound-2" style="visibility: hidden"></button>
<button type="button" id="devamet" class="btn btn-danger mb-control" data-box="#message-box-sound-3" style="visibility: hidden"></button>
<div class="message-box message-box-warning animated fadeIn" id="message-box-warning">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-warning"></span>Dikkat</div>
            <div class="mb-content">
                <p>Lütfen Cevap Şıkkı Seçiniz!!!</p>
            </div>
            <div class="mb-footer">
                <button class="btn btn-default btn-lg pull-right mb-control-close">Kapat</button>
            </div>
        </div>
    </div>
</div>
<div class="message-box message-box-danger animated fadeIn" data-sound="fail" id="message-box-sound-2">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span>Dikkat!</div>
            <div class="mb-content">
                <p>Test (Eğitim) bitiriyorsunuz. Eminmisiniz?</p>
            </div>
            <div class="mb-footer">
                <button class="btn btn-danger btn-lg pull-right mb-control-close" onclick="TestBitirManuel();">Evet</button>
                <button class="btn btn-default btn-lg pull-right mb-control-close">İptal</button>
            </div>
        </div>
    </div>
</div>

<div class="message-box message-box-danger animated fadeIn" data-sound="fail" id="message-box-sound-3">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span>Dikkat!</div>
            <div class="mb-content">
                <p>Soru için ayrılan süre tamamlandı !</p>
            </div>
            <div class="mb-footer">
                <button class="btn btn-default btn-lg pull-right mb-control-close" onclick="GetTipSoruDetayNull();">Devam</button>
            </div>
        </div>
    </div>
</div>


@*<script type="text/javascript" src="~/js/plugins/jquery/jquery.min.js"></script>*@

@section scripts{
<script>
    function showImage(typeId) {
        switch (typeId) {
            case 'P1':
                $('#rsmx').attr('style', 'filter: sepia(1);-webkit-filter: sepia(1) hue-rotate(180deg) saturate(2.3) contrast(220%); -moz-filter: sepia(1); -o-filter: sepia(1); -ms-filter: sepia(1);');
                break;
            case 'P2':
                $('#rsmx').attr('style', 'filter: sepia(1);-webkit-filter: saturate(2) sepia(1) hue-rotate(65deg) saturate(1.6) contrast(1.6)  brightness(2.5); -moz-filter: sepia(1); -o-filter: sepia(1); -ms-filter: sepia(1);');
                break;
            case 'P3':
                $('#rsmx').attr('style', 'filter: sepia(1);-webkit-filter: sepia(1) hue-rotate(180deg) saturate(3) contrast(2) hue-rotate(180deg)');
                break;
            case 'HI':
                $('#rsmx').attr('style', 'filter: saturate(80%); -webkit-filter: sepia(0) saturate(200%);-moz-filter: saturate(80%); -o-filter: saturate(80%); -ms-filter: saturate(80%);');
                break;
            case 'NEG':
                $('#rsmx').attr('style', '-webkit-filter: invert(100%); filter: invert(100%);');
                break;
            case 'SB':
                $('#rsmx').attr('style', '-webkit-filter: grayscale(100%); filter: grayscale(100%);');
                break;
            case 'BW':
                $('#rsmx').attr('style', '-webkit-filter: grayscale(100%) invert(100%); filter: grayscale(100%) invert(100%);');
                break;
            case 'SEN':
                $('#rsmx').attr('style', 'filter: sepia(1);-webkit-filter: sepia(1) grayscale(100%); -moz-filter: sepia(1); -o-filter: sepia(1); -ms-filter: sepia(1);');
                break;
            default:
                break;
        }

    }

    function defaultImage() {
        $('#rsmx').attr('style', 'height: 620px; visibility: visible; background-color: white;');
    }

    function GetTipSoruDetay(Tip_Ref, id, kayitmi) {

        if (kayitmi) {
            CevapKaydet();
        }
        else {
            $.get('@Url.Action("_TSoruDetay", "TipEgitimTest", new { area = "SINAV" })', { TipEgitim_Ref: Tip_Ref, idx: id, Kalansoru: '@kalansoru' }, function (data) {
            $("#seciliSoruIcerik").html(data);
        });
    }
}

function GetTipSoruDetayNull() {
    CevapKaydetNull();
}

function TestBitirManuel() {

    $.ajax({
        url: "/SINAV/TipEgitimTest/TipEgitimTestBitir",
        success: function (data) {
            //$.ajax({
            //    url: '/SIMULATOR/BagajInceleme/LogYaz',
            //    data: { 'islemTur': 2, 'simulatorRef': 4 },
            //    success: function () { }
            //});
            window.location.href = '/SINAV/TipSinav/Index?tst=true';
        },
        error: function (hata) {
            alert(hata.responseText);
        }
    });
}

$(function () {

    var surec = setInterval(function () {
        var a = "@bitisSaati";
            var b = displayTime();
            var difference = Math.abs(toSeconds(a) - toSeconds(b));
            if (Math.abs(toSeconds(a) >= toSeconds(b))) {
                var result = [
                    Math.floor(difference / 3600),
                    Math.floor((difference % 3600) / 60),
                    difference % 60
                ];
                result = result.map(function (v) {
                    return v < 10 ? '0' + v : v;
                }).join(':');
                $('#pulsate-regular').html(result);
                if (result == "00:00:00") {

                    clearInterval(surec);
                    TestBitirManuel();
                }
            }
            else {
                clearInterval(surec);
            }
        }, 1000);
        GetTipSoruDetay('@(SinavID)', '@sorunNo', false);
    });



    function displayTime() {
        var str = "";

        var currentTime = new Date()
        var hours = currentTime.getHours()
        var minutes = currentTime.getMinutes()
        var seconds = currentTime.getSeconds()

        if (minutes < 10) {
            minutes = "0" + minutes
        }
        if (seconds < 10) {
            seconds = "0" + seconds
        }
        str += hours + ":" + minutes + ":" + seconds + " ";
        return str;
    }

    function toSeconds(time_str) {
        var parts = time_str.split(':');
        return parts[0] * 3600 +
        parts[1] * 60 +
        +
        parts[2];
    }




</script>
    }